try {
x = 5
}
catch (IOException e) {
Console.Write("error");
}
finally {
Console.Write("whatever");
}
